# Jekyll configuration
title: Şahmat
description: Modern ve minimalist bir satranç dergisi.
baseurl: ""
url: "https://sahmat.com"

# Build settings
markdown: kramdown

# Exclude list for GitHub Pages
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - eleventy.config.js
  - .env.example
  - dist
  - vendor
